package javaproject;
// Generated Feb 21, 2023, 7:16:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {


     private long id;
     private Ciclos ciclos;
     private Docentes docentes;
     private String nombre;
     private Set estudiantesAsignaturas = new HashSet(0);
     private Set registroasistenciases = new HashSet(0);

    public Asignaturas() {
    }

	
    public Asignaturas(long id, Ciclos ciclos, Docentes docentes, String nombre) {
        this.id = id;
        this.ciclos = ciclos;
        this.docentes = docentes;
        this.nombre = nombre;
    }
    public Asignaturas(long id, Ciclos ciclos, Docentes docentes, String nombre, Set estudiantesAsignaturas, Set registroasistenciases) {
       this.id = id;
       this.ciclos = ciclos;
       this.docentes = docentes;
       this.nombre = nombre;
       this.estudiantesAsignaturas = estudiantesAsignaturas;
       this.registroasistenciases = registroasistenciases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ciclos getCiclos() {
        return this.ciclos;
    }
    
    public void setCiclos(Ciclos ciclos) {
        this.ciclos = ciclos;
    }
    public Docentes getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Docentes docentes) {
        this.docentes = docentes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEstudiantesAsignaturas() {
        return this.estudiantesAsignaturas;
    }
    
    public void setEstudiantesAsignaturas(Set estudiantesAsignaturas) {
        this.estudiantesAsignaturas = estudiantesAsignaturas;
    }
    public Set getRegistroasistenciases() {
        return this.registroasistenciases;
    }
    
    public void setRegistroasistenciases(Set registroasistenciases) {
        this.registroasistenciases = registroasistenciases;
    }




}


