package javaproject;
// Generated Feb 21, 2023, 7:16:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carreras generated by hbm2java
 */
public class Carreras  implements java.io.Serializable {


     private long id;
     private Facultades facultades;
     private String nombre;
     private Set cicloses = new HashSet(0);

    public Carreras() {
    }

	
    public Carreras(long id, Facultades facultades, String nombre) {
        this.id = id;
        this.facultades = facultades;
        this.nombre = nombre;
    }
    public Carreras(long id, Facultades facultades, String nombre, Set cicloses) {
       this.id = id;
       this.facultades = facultades;
       this.nombre = nombre;
       this.cicloses = cicloses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Facultades getFacultades() {
        return this.facultades;
    }
    
    public void setFacultades(Facultades facultades) {
        this.facultades = facultades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCicloses() {
        return this.cicloses;
    }
    
    public void setCicloses(Set cicloses) {
        this.cicloses = cicloses;
    }




}


