package javaproject;
// Generated Feb 20, 2023, 7:40:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos  implements java.io.Serializable {


     private long id;
     private Carreras carreras;
     private Matriculas matriculas;
     private int numero;
     private Set asignaturases = new HashSet(0);

    public Ciclos() {
    }

	
    public Ciclos(long id, Carreras carreras, Matriculas matriculas, int numero) {
        this.id = id;
        this.carreras = carreras;
        this.matriculas = matriculas;
        this.numero = numero;
    }
    public Ciclos(long id, Carreras carreras, Matriculas matriculas, int numero, Set asignaturases) {
       this.id = id;
       this.carreras = carreras;
       this.matriculas = matriculas;
       this.numero = numero;
       this.asignaturases = asignaturases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public Matriculas getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Matriculas matriculas) {
        this.matriculas = matriculas;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Set getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set asignaturases) {
        this.asignaturases = asignaturases;
    }




}


