package javaproject;
// Generated Feb 21, 2023, 7:16:14 PM by Hibernate Tools 4.3.1



/**
 * EstudiantesAsignatura generated by hbm2java
 */
public class EstudiantesAsignatura  implements java.io.Serializable {


     private long id;
     private Asignaturas asignaturas;
     private Estudiantes estudiantes;

    public EstudiantesAsignatura() {
    }

    public EstudiantesAsignatura(long id, Asignaturas asignaturas, Estudiantes estudiantes) {
       this.id = id;
       this.asignaturas = asignaturas;
       this.estudiantes = estudiantes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }




}


