package javaproject;
// Generated Feb 20, 2023, 7:40:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {
     private long id;
     private Usuarios usuarios;
     private String nombre;
     private int edad;
     private Set registroasistenciases = new HashSet(0);

    public Estudiantes() {
    }

    public Estudiantes(long id, String nombre, int edad) {
        this.id = id;
        this.nombre = nombre;
        this.edad = edad;
    }
    public Estudiantes(long id, Usuarios usuarios, String nombre, int edad, Set registroasistenciases) {
       this.id = id;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.edad = edad;
       this.registroasistenciases = registroasistenciases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Set getRegistroasistenciases() {
        return this.registroasistenciases;
    }
    
    public void setRegistroasistenciases(Set registroasistenciases) {
        this.registroasistenciases = registroasistenciases;
    }




}


