package javaproject;
// Generated Feb 20, 2023, 7:40:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facultades generated by hbm2java
 */
public class Facultades  implements java.io.Serializable {


     private long id;
     private Universidades universidades;
     private String nombre;
     private Set carrerases = new HashSet(0);

    public Facultades() {
    }

	
    public Facultades(long id, Universidades universidades, String nombre) {
        this.id = id;
        this.universidades = universidades;
        this.nombre = nombre;
    }
    public Facultades(long id, Universidades universidades, String nombre, Set carrerases) {
       this.id = id;
       this.universidades = universidades;
       this.nombre = nombre;
       this.carrerases = carrerases;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Universidades getUniversidades() {
        return this.universidades;
    }
    
    public void setUniversidades(Universidades universidades) {
        this.universidades = universidades;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCarrerases() {
        return this.carrerases;
    }
    
    public void setCarrerases(Set carrerases) {
        this.carrerases = carrerases;
    }




}


