package javaproject;
// Generated Feb 20, 2023, 7:40:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registroasistencias generated by hbm2java
 */
public class Registroasistencias  implements java.io.Serializable {


     private long id;
     private Asignaturas asignaturas;
     private Estudiantes estudiantes;
     private Date fecha;

    public Registroasistencias() {
    }

    public Registroasistencias(long id, Asignaturas asignaturas, Estudiantes estudiantes, Date fecha) {
       this.id = id;
       this.asignaturas = asignaturas;
       this.estudiantes = estudiantes;
       this.fecha = fecha;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


