package javaproject;
// Generated Feb 20, 2023, 7:40:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Universidades generated by hbm2java
 */
public class Universidades  implements java.io.Serializable {


     private long id;
     private String nombre;
     private String direccion;
     private Set facultadeses = new HashSet(0);

    public Universidades() {
    }

	
    public Universidades(long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Universidades(long id, String nombre, String direccion, Set facultadeses) {
       this.id = id;
       this.nombre = nombre;
       this.direccion = direccion;
       this.facultadeses = facultadeses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getFacultadeses() {
        return this.facultadeses;
    }
    
    public void setFacultadeses(Set facultadeses) {
        this.facultadeses = facultadeses;
    }




}


